### ISSUE TITLE
ExtensibilityTools causes exception when loading a solution in VS 2015

### ISSUE THREAD

**Issue by brhinescot** [madskristensen/ExtensibilityTools#12]
When loading a solution I always get an exception dialog saying "An exception has been encountered. This may be caused by an extension.". 

Disabling this extension stops the exception from occurring.

The only error in ActivityLog.xml is the following:

  <entry>
    <record>691</record>
    <time>2015/04/28 18:55:18.911</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at MadsKristensen.ExtensibilityTools.EditorMargin.BottomMarginFactory.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer) in c:\projects\extensibilitytools\src\EditorMargin\BottomMarginFactory.cs:line 27&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__3(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)</description>
  </entry>

I have VS 2015 CTP 6 but this has happened with other versions.

I can add the entire ActivityLog.xml text if it would be helpful.

**Comment by madskristensen** [comment]
What solution are you opening? MVC, C++, C# console app, or...?

**Comment by brhinescot** [comment]
One solution has 2 MVC 6 projects. Another solution is a mixture of traditional class libraries, NUnit test projects and an MVC 5 project. All are C#.

**Comment by madskristensen** [comment]
What file do you have open in the editor when the solution opens? A .cs file or...?

**Comment by madskristensen** [comment]
Actually, I think I fixed this issue a while back. Are you running the latest version (1.0.52)?

**Comment by madskristensen** [comment]
Ok, I made a change. Can you please try the new build here http://vsixgallery.com/extension/f8330d54-0469-43a7-8fc0-7f19febeb897/ and see if it solved the issue?

**Comment by brhinescot** [comment]
Thanks but still get it. I do have the version you liked to installed. Opening VS without a file open is OK. I then opened a HTML file and the exception occurred. I tried again with a js file after restarting with the same result. Here is the log for the event:

  <entry>
    <record>765</record>
    <time>2015/04/28 23:29:25.602</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at MadsKristensen.ExtensibilityTools.EditorMargin.BottomMarginFactory.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer) in c:\projects\extensibilitytools\src\EditorMargin\BottomMarginFactory.cs:line 27&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__3(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)</description>
  </entry>

**Comment by brhinescot** [comment]
The only extension I have that isn't one of yours that may modify editors is Resharper.

**Comment by madskristensen** [comment]
Was this the build you tried? http://vsixgallery.com/extension/f8330d54-0469-43a7-8fc0-7f19febeb897/ 

I wonder if ReSharper could cause the extension to fail. That would explain why I can't reproduce the issue. Can you try to disable ReSharper just to see if that fixes it?

**Comment by brhinescot** [comment]
Yeah, I verified the build is 1.0.62 in extension manager. I disabled Resharper and still got it. I'll try uninstalling it.

**Comment by brhinescot** [comment]
Still no luck unfortunately. It isn't a show stopper though, VS still works.

**Comment by AndreSayreMSFT** [comment]
@madskristensen I'm getting the exact same error in the Activity log as @brhinescot on my machine; No ReSharper.  Shows on opening C# projects [The PoshTools Extension .sln if curious :)]  Using the build you posted 3 comments up.

Need access to my repro box/project?

**Comment by somewhatabstract** [comment]
I have a similar issue with the current version, but it gives this error in the ActivityLog.xml

I am on 2015 RC and Extensibility Tools version 1.0.52

`SetSite failed for package [ExtensibilityToolsPackage]`

**Comment by madskristensen** [comment]
I think it's all fixed now. Build 1.0.63 should be ready in a few minutes for testing right here http://vsixgallery.com/extension/f8330d54-0469-43a7-8fc0-7f19febeb897/

**Comment by madskristensen** [comment]
Nope, didn't work. I'll try another approach. Stay tuned

**Comment by phofman** [comment]
Isn't the problem related to enforced version 12.0.0.0 of following reference libs:
`Microsoft.VisualStudio.TextTemplating.VSHost.12.0.dll`, `Microsoft.VisualStudio.Text.UI.dll` and `Microsoft.VisualStudio.Text.UI.Wpf.dll`. They probably don't exist, when you have only VS14 installed, causing runtime nulls.

I personally had lots of fun with such situations, when developing my plugins, always ending up with dedicated solution per VisulStudio version to fix references etc.

**Comment by phofman** [comment]
Clearer: change `Specific Version` to false.

![ref-lib](https://cloud.githubusercontent.com/assets/475630/8146263/f03d443e-122e-11e5-8bea-a724745feaf5.png)

**Comment by madskristensen** [comment]
Visual Studio has binding redirects for most of these assemblies so they get upgraded automatically to *.14.dll. But yes, it could very well be the issue. If I can't figure it out, this extension will be 2015 only

**Comment by madskristensen** [comment]
I got it to load correctly now, but for some reason there are errors loading the Options page. I've never had issues with that before

**Comment by madskristensen** [comment]
Ok, I've given up. it works fine now if I limit the extension to only work in VS2015. That's what I've done and will be releasing an update shortly

**Comment by Nafees060** [comment]
Thank you sir problem solved

**Comment by RickyMartin12** [comment]
i have a same problem when i open the VS 2015 and i installed the ExtensibilityTools 2015 and i have the same problem

The problem is

"An exception has been encountered. This may be caused by an extension.".

You can get more information by examining the file

'C:\Users\Ricardo\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml'

**Comment by madskristensen** [comment]
@RickyMartin12 Can you please send the error listed in the ActivityLog.xml file?

**Comment by jimior2** [comment]
I have the same issue, could I send you the activitylog.xml?

**Comment by Shujee** [comment]
Same issue here too, but I see it in Blend for Visual Studio 2015. Activity.log attached.

[ActivityLog.zip](https://github.com/madskristensen/ExtensibilityTools/files/560142/ActivityLog.zip)

**Comment by nareshkumarkatta** [comment]
Hi @madskristensen, same issue here in VS 2015, but this time the exception is different. I'm totally new to visual studio please help me out. ActivityLog is attached.



[ActivityLog.txt](https://github.com/madskristensen/ExtensibilityTools/files/587376/ActivityLog.txt)

**Comment by mshwf** [comment]
I got this error when I delete some attributes from HTML element inserted by using the snippet (double tab) when I select some attributes and press Delete or Backspace.
Also when I move the cursor to a specific attribute to delete it, it moves automatically to the previous attribute's value so there is a good chance that I delete it by mistake. That all happens due to the snippet auto insertion, if I pressed Esc after the auto insertion the element behaves normally, but I will not be able to move through attributes using Tab key.

**Comment by psoszynski** [comment]
Same issue in VS2017!

**Comment by imshamim** [comment]
we are also getting same issue as above screen shot, in win7 sp1 Visual Studio 2017.

**Comment by tabruzzomufg** [comment]
is there a solution to this problem, i can't code with this problem....
